# Import tasks and environment from other files
import = [
   "build/scripts/build.toml", 
   "build/scripts/test.toml",
   "build/scripts/publish.toml"
]

[project]
name = "maid"
version = "2.0.0"

# Build on a remote server
[project.server]
address = { host = "localhost", port = 3500, ssl = false }
token = "test_token1"

# Global environment (applied to shell)
[env]
BOOL = false
STRING = 'test'
TYPE = '%{dir.home} %{env.STRING} %{arg.1}'
ARR = ['hello', 'world']
VERSION='1.2.1'

[tasks.build]
info = "Build binaries"
depends = ["clean"]
script = [
   "cargo zigbuild --release --color always", 
   "mv target/release/maid bin/maid",
   "mv target/release/maid-server bin/maid-server",
]

[tasks.build.cache]
path = "maid"
target = ["bin/maid", "bin/maid-server"]

# [tasks.build.remote]
# silent = false
# exclusive = false
# shell = "/bin/bash"
# image = "messense/cargo-zigbuild:latest"
# push = ["crates", "Cargo.toml", "Cargo.lock"]
# pull = "bin"

# Basic task definition 
[tasks]
api_server = { depends = ["build"], script = "./maid_server", path = "bin" }
clean = { info = "Clean binary files", script = ["rm -rf bin", "mkdir bin"] }
install = { info = "Move binary file", script = ["maid build -q","sudo cp bin/maid /usr/local/bin", "maid -V"] }